"""your message here

Revision ID: 1c9ab2cfe106
Revises: e1fdc15ca0ea
Create Date: 2024-05-24 09:04:01.057340

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c9ab2cfe106"
down_revision: Union[str, None] = "e1fdc15ca0ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
