"""your message here

Revision ID: 224be2bff8db
Revises: 1c9ab2cfe106
Create Date: 2024-05-24 09:05:23.427242

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "224be2bff8db"
down_revision: Union[str, None] = "1c9ab2cfe106"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
